<a href="https://colab.research.google.com/github/malavikasreekumar/Iris-flower-/blob/master/Iris_flower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [3]:
cd gdrive

/content/gdrive


In [4]:
cd My Drive

/content/gdrive/My Drive


In [5]:
cd Iris

/content/gdrive/My Drive/Iris


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('Iris.csv')
X=df.iloc[:,1:5].values
y=df.iloc[:,5].values

In [7]:
X


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)


# **Logistic Regression**

In [21]:
from sklearn.linear_model import LogisticRegression
lr_classifier=LogisticRegression(random_state=0)
lr_classifier.fit(X_train,y_train)


lr_pred=lr_classifier.predict(X_test)


from sklearn.metrics import confusion_matrix,accuracy_score
lr_cm=confusion_matrix(y_test,lr_pred)
from sklearn import metrics
print("Accuracy=",metrics.accuracy_score(y_test, lr_pred))

print(lr_cm)


Accuracy= 1.0
[[16  0  0]
 [ 0 14  0]
 [ 0  0 15]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# **K Nearest Neighbours** 

In [27]:

# Fitting classifier to the Training set
from sklearn.neighbors import KNeighborsClassifier
knn_classifier=KNeighborsClassifier(n_neighbors=3,metric='manhattan',p=2)
knn_classifier.fit(X_train, y_train)
# Create your classifier here

# Predicting the Test set results
knn_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
knn_cm = confusion_matrix(y_test, knn_pred)


from sklearn.metrics import confusion_matrix,accuracy_score
lr_cm=confusion_matrix(y_test,knn_pred)
from sklearn import metrics
print("Accuracy=",metrics.accuracy_score(y_test, knn_pred))

print(knn_cm)


Accuracy= 0.9777777777777777
[[16  0  0]
 [ 0 13  1]
 [ 0  0 15]]


# **Support Vector Machine**

In [28]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
svc_classifier = SVC(kernel = 'linear', random_state = 0)
svc_classifier.fit(X_train, y_train)

# Predicting the Test set results
svc_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
svc_cm = confusion_matrix(y_test, svc_pred)


from sklearn.metrics import confusion_matrix,accuracy_score
svc_cm=confusion_matrix(y_test,svc_pred)
from sklearn import metrics
print("Accuracy=",metrics.accuracy_score(y_test, svc_pred))

print(svc_cm)


Accuracy= 0.9777777777777777
[[16  0  0]
 [ 0 13  1]
 [ 0  0 15]]


# **Decision Tree**

In [34]:
# Fitting classifier to the Training set\
from sklearn.tree import DecisionTreeClassifier
dtree_classifier=DecisionTreeClassifier(criterion='entropy')
dtree_classifier.fit(X_train,y_train)
# Create your classifier here

# Predicting the Test set results
dtree_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
dtree_cm = confusion_matrix(y_test, dtree_pred)

dtree_cm=confusion_matrix(y_test,dtree_pred)
from sklearn import metrics
print("Accuracy=",metrics.accuracy_score(y_test, dtree_pred))

print(svc_cm)


Accuracy= 0.9777777777777777
[[16  0  0]
 [ 0 13  1]
 [ 0  0 15]]


In [36]:
# Fitting classifier to the Training set
from sklearn.naive_bayes import GaussianNB
nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)
# Create your classifier here

# Predicting the Test set results
nb_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
nb_cm = confusion_matrix(y_test, nb_pred)


from sklearn import metrics
print("Accuracy=",metrics.accuracy_score(y_test, svc_pred))

print(nb_cm)

Accuracy= 0.9777777777777777
[[16  0  0]
 [ 0 13  1]
 [ 0  0 15]]
